RUBYJS_GEN=/home/mneumann/Projects/rubyjs/rubyjs_gen
OPTS=--opt NoMethodMissing --opt NoArgumentArityChecks --opt OptimizeArithOps 

all:
	$(RUBYJS_GEN) ${OPTS} ${PLATFORM} --main HelloWorld hw.rb > hw.js
